# Generated by Django 3.1.7 on 2021-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
